n=int(input("how many elements you want insert: "))
input_list=input("enter number using space: ")
user_list=input_list.split()
print("list: ",user_list)
print("The second last item of the list is: ",user_list[n-2])